import {Outfit, Figtree, JetBrains_Mono} from "next/font/google";
import "./globals.css";
import localFont from 'next/font/local'
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/next"

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ['latin'],
  variable: '--font-jetbrains',
  display: 'swap',
});

const doto = localFont({
  src: './fonts/Doto-Bold.ttf',
    variable: '--font-doto',
  display: 'swap', // Optional but recommended for performance
})

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
  display: "swap",
});

export const metadata = {
  title: "rithu",
  description: "Generated by rithu",
  icons:{
    icon:"/favicon.jpg"
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${figtree.variable} ${jetbrainsMono.variable} ${doto.variable} flex flex-col min-h-screen antialiased`}
      >
        <Navbar/>
         <main className="flex-1">
          {children}
          <Analytics/>
         </main>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
